version: "3.7"
services:

        db:
         image: "postgres:latest"
         container_name: "postgressql"
         enviroment:
          POSTGRES_PASSWORD: "db_postgres"
          POSTGRES_USER: "postgres"
         ports:
          - "5432:5432"
         volumes:
          - db_postgres:/var/lib/postgresql/data
         networks: 
          - exql-network
          
        app:
         image: "exql:1.0"
         container_name: "express-graphql"
         depends_on: 
          - db
         enviroment: 
          - KNEX_CLIENT:pg
          - DB_NAME:boilerplate
          - DB_PASWWORD:db_postgres
          - DB_PORT:5432
          - PORT:1212
          - HOST:postgressql
         ports: 
          - "1212:1212"
         networks: 
          - exql-network 

networks: 
 exql-network:
  name: exql-network
volumes:
        db_postgres:
