version: "3.7"
services:

        postgressql:
         image: postgres
         container_name: postgressql
         environment:
          POSTGRES_PASSWORD: postgrespassword
          POSTGRES_USER: root
          POSTGRES_DB: boilerplate
         ports:
          - 5432:5432
         volumes:
          - ./pgdata:/var/lib/postgresql/data
         networks:
          - exql-network

        express-graphql:
         image: exql:1.0
         container_name: express-graphql
         depends_on:
          - postgressql
         environment:
          - KNEX_CLIENT=pg
          - DB_NAME=boilerplate
          - DB_USERNAME=root
          - DB_PASSWORD=postgrespassword
          - DB_PORT=5432
          - PORT=1212
          - HOST=postgressql
         ports:
          - 1212:1212
         networks:
          - exql-network
networks:
 exql-network:
  name: exql-network
volumes:
        pgdata:

