version: "3.7"
services:

        db:
         image: "postgres:latest"
         container_name: "postgressql"
         environment:
          POSTGRES_PASSWORD: "db_postgres"
          POSTGRES_USER: "postgres"
         ports:
          - "5432:5432"
         volumes:
          - db_postgres:/var/lib/postgresql/data

volumes:
        db_postgres:

